CREATE TABLE ROL_EXTRANET (
    RE_ID INT(4) NOT NULL AUTO_INCREMENT,
    RE_NOMBRE_ROL VARCHAR(50) NOT NULL,
    RE_PRIMARY KEY (ID)
);

CREATE TABLE USUARIO_EXTRANET (
    UE_ID INT(10) NOT NULL AUTO_INCREMENT,
    UE_EMAIL VARCHAR(255) NOT NULL,
    UE_PASS VARCHAR(255) NOT NULL,
    UE_NOMBRE VARCHAR(200),
    UE_APELLIDOS VARCHAR(200),
	UE_FECHA_ALTA DATE,
    UE_GESTION BIT(1),
    UE_ID_ROL INT(4),
    UE_PRIMARY KEY (ID),
    UE_FOREIGN KEY (ID_ROL) REFERENCES ROL_EXTRANET(ID)
);